version: '3'
services:
  # Server
  softeng-nginx:
    image: victorhad/softeng:nginx
    container_name: softeng-nginx
    ports:
      - "8000:8000"
    depends_on:
      - softeng-prod

  # Production enviroment
  softeng-prod:
    image: victorhad/softeng:latest
    container_name: softeng-prod
    depends_on:
      - db

  # Postgresql database
  db:
    image: postgres
    container_name: softeng-db

  # Sesame triplestore
  sesame:
    image: victorhad/softeng:sesame
    container_name: sesame
    ports:
      - "8001:8080"
