version: '3'
services:
  # Production enviroment
  softeng-prod:
    image: victorhad/softeng:latest
    build:
      context: .
      dockerfile: ./compose/production/Dockerfile

  # NGINX to production
  softeng-nginx:
    image: victorhad/softeng:nginx
    build:
      context: .
      dockerfile: ./compose/nginx/Dockerfile

  # Sesame triplestore
  sesame:
    image: victorhad/softeng:sesame
    build:
      context: .
      dockerfile: ./compose/sesame/Dockerfile
