version: '3'
services:
  # Sesame triplestore to local enviroment
  sesame:
    image: victorhad/softeng:sesame
    container_name: sesame-local
    build:
      context: .
      dockerfile: ./compose/sesame/Dockerfile
    ports:
      - "8001:8080"
