version: '3'
services:
  # Homolog enviroment
  softeng-local:
    image: victorhad/softeng:local
    container_name: softeng
    build:
      context: .
      dockerfile: ./compose/local/Dockerfile
    ports:
      - "8000:8000"
