# Generated by Django 2.0.6 on 2018-06-23 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Knowledge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Knowledge title.', max_length=100, verbose_name='Title')),
                ('description', models.TextField(blank=True, help_text='Knowledge description.', verbose_name='Description')),
                ('slug', models.SlugField(help_text='URL string shortcut', verbose_name='Shortcut')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date that the knowledge is created.', verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date that the knowledge is updated.', verbose_name='Updated at')),
            ],
            options={
                'verbose_name_plural': 'Knowledges',
                'verbose_name': 'Knowledge',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Subtopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Subtopic title.', max_length=100, verbose_name='Title')),
                ('description', models.TextField(blank=True, help_text='Subtopic description.', verbose_name='Description')),
                ('slug', models.SlugField(help_text='URL string shortcut', verbose_name='Shortcut')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date that the subtopic is created.', verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date that the subtopic is updated.', verbose_name='Updated at')),
            ],
            options={
                'verbose_name_plural': 'Subtopics',
                'verbose_name': 'Subtopic',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Topic title.', max_length=100, verbose_name='Title')),
                ('description', models.TextField(blank=True, help_text='Topic description.', verbose_name='Description')),
                ('slug', models.SlugField(help_text='URL string shortcut', verbose_name='Shortcut')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date that the topic is created.', verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date that the topic is updated.', verbose_name='Updated at')),
                ('knowledge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='knowledge.Knowledge')),
            ],
            options={
                'verbose_name_plural': 'Topics',
                'verbose_name': 'Topic',
                'ordering': ['title'],
            },
        ),
        migrations.AddField(
            model_name='subtopic',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtopics', to='knowledge.Topic'),
        ),
    ]
