# Generated by Django 2.0.6 on 2018-06-24 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0004_abstraction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='knowledge',
            name='core_content',
        ),
    ]
