# Generated by Django 2.0.6 on 2018-06-25 02:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('knowledge', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoreContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Core content title.', max_length=100, verbose_name='Title')),
                ('description', models.TextField(blank=True, help_text='Core content description.', verbose_name='Description')),
                ('slug', models.SlugField(help_text='URL string shortcut', verbose_name='Shortcut')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date that the core content is created.', verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date that the core content is updated.', verbose_name='Updated at')),
            ],
            options={
                'verbose_name': 'Core Content',
                'verbose_name_plural': 'Core Contents',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Discipline title.', max_length=100, verbose_name='Title')),
                ('code', models.PositiveIntegerField(help_text='Discipline code.', unique=True, verbose_name='Code')),
                ('institution', models.CharField(help_text='Discipline institution', max_length=100, verbose_name='Institution')),
                ('semester', models.PositiveIntegerField(choices=[(1, 'First Semester'), (2, 'Second Semester'), (3, 'Third Semester'), (4, 'Fourth Semester'), (5, 'Fifth Semester'), (6, 'Sixth Semester'), (7, 'Seventh Semester'), (8, 'Eighth Semester'), (9, 'Ninth Semester'), (10, 'Tenth Semester')], help_text='Discipline semester.', verbose_name='Semester')),
                ('classification', models.CharField(choices=[('Required', 'Required'), ('Optional', 'Optional')], default='Required', help_text='Discipline classification.', max_length=8, verbose_name='Classification')),
                ('description', models.TextField(blank=True, help_text='Discipline description.', verbose_name='Description')),
                ('credits', models.PositiveIntegerField(blank=True, help_text='Discipline credits', verbose_name='Credits')),
                ('bibliografy', models.TextField(blank=True, help_text='Bibliografy', verbose_name='Bibliografy')),
                ('slug', models.SlugField(help_text='URL string shortcut', unique=True, verbose_name='Shortcut')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date that the discipline is created.', verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date that the discipline is updated.', verbose_name='Updated at')),
                ('core_content', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disciplines', to='curriculum.CoreContent')),
            ],
            options={
                'verbose_name': 'Discipline',
                'verbose_name_plural': 'Disciplines',
                'ordering': ['semester'],
            },
        ),
        migrations.CreateModel(
            name='Extension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Core content title.', max_length=100, verbose_name='Title')),
                ('description', models.TextField(blank=True, help_text='Core content description.', verbose_name='Description')),
                ('slug', models.SlugField(help_text='URL string shortcut', verbose_name='Shortcut')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date that the core content is created.', verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date that the core content is updated.', verbose_name='Updated at')),
            ],
            options={
                'verbose_name': 'Extension',
                'verbose_name_plural': 'Extensions',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Multidisciplinary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Core content title.', max_length=100, verbose_name='Title')),
                ('description', models.TextField(blank=True, help_text='Core content description.', verbose_name='Description')),
                ('slug', models.SlugField(help_text='URL string shortcut', verbose_name='Shortcut')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date that the core content is created.', verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date that the core content is updated.', verbose_name='Updated at')),
            ],
            options={
                'verbose_name': 'Multidisciplinary',
                'verbose_name_plural': 'Multidisciplinary',
                'ordering': ['title'],
            },
        ),
        migrations.AddField(
            model_name='discipline',
            name='multidisciplinary',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disciplines', to='curriculum.Multidisciplinary'),
        ),
        migrations.AddField(
            model_name='discipline',
            name='program',
            field=models.ManyToManyField(blank=True, related_name='disciplines', to='knowledge.Subtopic'),
        ),
        migrations.AddField(
            model_name='discipline',
            name='required',
            field=models.ManyToManyField(blank=True, related_name='is_required_in', to='curriculum.Discipline'),
        ),
    ]
