# Generated by Django 2.0.6 on 2018-06-23 23:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Discipline title.', max_length=100, verbose_name='Title')),
                ('code', models.PositiveIntegerField(help_text='Discipline code.', verbose_name='Code')),
                ('institution', models.CharField(blank=True, help_text='Discipline institution', max_length=100, verbose_name='Institution')),
                ('semester', models.PositiveIntegerField(choices=[(1, 'First Semester'), (2, 'Second Semester'), (3, 'Third Semester'), (4, 'Fourth Semester'), (5, 'Fifth Semester'), (6, 'Sixth Semester'), (7, 'Seventh Semester'), (8, 'Eighth Semester'), (9, 'Ninth Semester'), (10, 'Tenth Semester')], help_text='Discipline semester.', verbose_name='Semester')),
                ('classification', models.CharField(choices=[('Required', 'Required'), ('Optional', 'Optional')], default='Required', help_text='Discipline classification.', max_length=8, verbose_name='Classification')),
                ('description', models.TextField(blank=True, help_text='Discipline description.', verbose_name='Description')),
                ('credits', models.PositiveIntegerField(help_text='Discipline credits', validators=[django.core.validators.MaxLengthValidator(10), django.core.validators.MinLengthValidator(1)], verbose_name='Credits')),
                ('bibliografy', models.TextField(blank=True, help_text='Bibliografy', verbose_name='Bibliografy')),
                ('slug', models.SlugField(help_text='URL string shortcut', verbose_name='Shortcut')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date that the discipline is created.', verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date that the discipline is updated.', verbose_name='Updated at')),
                ('required', models.ManyToManyField(blank=True, related_name='is_required_in', to='curriculum.Discipline')),
            ],
            options={
                'verbose_name_plural': 'Disciplines',
                'verbose_name': 'Discipline',
                'ordering': ['semester'],
            },
        ),
    ]
