# Generated by Django 2.0.6 on 2018-06-23 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0001_initial'),
        ('curriculum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='discipline',
            name='program',
            field=models.ManyToManyField(blank=True, related_name='disciplines', to='knowledge.Subtopic'),
        ),
    ]
