# Generated by Django 2.0.6 on 2018-06-25 03:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0004_multidiciplinary_fixture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discipline',
            name='core_content',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disciplines', to='curriculum.CoreContent'),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='multidisciplinary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disciplines', to='curriculum.Multidisciplinary'),
        ),
    ]
