# Generated by Django 2.0.6 on 2018-06-24 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0005_remove_knowledge_core_content'),
        ('curriculum', '0005_auto_20180624_0631'),
    ]

    operations = [
        migrations.AddField(
            model_name='discipline',
            name='program',
            field=models.ManyToManyField(blank=True, related_name='disciplines', to='knowledge.Subtopic'),
        ),
    ]
