# Generated by Django 2.0.6 on 2018-06-24 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0006_discipline_program'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discipline',
            name='code',
            field=models.PositiveIntegerField(help_text='Discipline code.', unique=True, verbose_name='Code'),
        ),
    ]
