# Generated by Django 2.0.6 on 2018-06-24 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0007_auto_20180624_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discipline',
            name='slug',
            field=models.SlugField(help_text='URL string shortcut', unique=True, verbose_name='Shortcut'),
        ),
    ]
