# Generated by Django 2.0.6 on 2018-06-25 00:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0008_auto_20180624_2001'),
    ]

    operations = [
        migrations.AddField(
            model_name='discipline',
            name='multidisciplinary',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disciplines', to='curriculum.Multidisciplinary'),
        ),
    ]
