# Generated by Django 2.0.6 on 2018-06-25 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0009_discipline_multidisciplinary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discipline',
            name='credits',
            field=models.PositiveIntegerField(blank=True, help_text='Discipline credits', verbose_name='Credits'),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='institution',
            field=models.CharField(help_text='Discipline institution', max_length=100, verbose_name='Institution'),
        ),
    ]
